version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
        - "api"
    image: api
    restart: no
    ports:
      - 8888:8888
    depends_on:
      postgres:
        condition: service_started
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main

volumes:
  pgdata: {}
